### ISSUE TITLE
Setup formatting check in CI

### ISSUE THREAD

**Issue by doriath** [beancount/beanquery#10]
I hate doing manual formatting of the code, what do you think about deciding on some auto formatter and enforcing it?

I was thinking about using https://github.com/google/yapf, but I am not sure if I should use `pep8` (default) or `google`. Any preferences?

**Comment by blais** [comment]
Really not a fan of automated formatting.
I have a lot of order in code that gets undone.

Last time I checked for those things Python Black was the thing. Don't know
how it has held up.

**Comment by dnicolodi** [comment]
I am also not a fan of automated formatting. If we really, really, really need one, Black https://pypi.org/project/black/ is still the thing for Python.

**Comment by doriath** [comment]
Ok, if you prefer not to have auto-formatting, lets close this issue.
