### ISSUE TITLE
value(position) when generating balance for previous FY

### ISSUE THREAD

**Issue by muks** [beancount/beanquery#107]
When generating the balance of an account (at market value for presentation in a management report) for a previous financial year, e.g., ending on 2021-03-31, we may use the following `bean-query` SQL statement:

```sql
SELECT sum(value(position)) FROM CLOSE ON 2021-04-01 CLEAR WHERE account ~ '^Assets:Current:Cash-And-Short-Term-Deposits';
```

Assume the journal input contains price statements such as:
```
2021-03-31 price USD 1.3472 SGD
2022-03-31 price USD 1.3534 SGD
```

Unfortunately, the query above seems to use `price` statements that came after 2021-03-31 to compute the market value of the position (it seems to use the most recent `price` statement in the journal input which is from 2022-03-31). It does not appear to regard the `CLOSE ON 2021-04-01` to limit looking for prices. I'm not able to generate a table of balances of this year and the previous year in a management report, where the previous year's balances have to match the market rates on that financial year's closing reporting date.

I don't know if this is a bug, or if some other clause has to be used to make `bean-query` limit looking for `price` statements up to 2021-03-31. Please can you advise?

**Comment by muks** [comment]
I'll answer my own question. I have to use:
```sql
SELECT sum(value(position, 2021-04-01)) FROM CLOSE ON 2021-04-01 CLEAR WHERE account ~ '^Assets:Current:Cash-And-Short-Term-Deposits';
```

**Comment by dnicolodi** [comment]
It is always useful to include a minimal ledger file that reproducing the issue when reporting bugs or asking for advice. 

Both using the current price or the historical price are valid behaviors and I see use cases for both. If you need the value at a specific date, you need the two argument version of the `value` function:
```
SELECT
  sum(value(position, 2021-03-31)) 
FROM
  CLOSE ON 2021-04-01 CLEAR
WHERE 
  account ~ '^Assets:Current:Cash-And-Short-Term-Deposits'
```
Also, maybe you want to replace the regular expression match with the use of the `root()` function:
```
SELECT
  sum(value(position, 2021-03-31)) 
FROM
  CLOSE ON 2021-04-01 CLEAR
WHERE 
  root(account, 2) = 'Assets:Current:Cash-And-Short-Term-Deposits'
```

**Comment by muks** [comment]
Thank you for the tips with examples @dnicolodi.
