### ISSUE TITLE
bean-query returns an improper balance if date >= is specified

### ISSUE THREAD

**Issue by AlphaJack** [beancount/beanquery#150]
I noticed that bean-query returns a different "balance" for the first entry of a query if `date >=` is specified.
It does not take into account the balance of the previous period (since it is excluded from the query), and uses the change of the first period as balance.
This impacts all other entries, as subsequent balances are calculated from the first one.

## Setup

```bash
bean-example --date-begin 2020-01-01 --date-end 2022-12-31 --seed 0 > example.beancount

# wrong result for all the entries
bean-query --numberify --format csv "example.beancount" "select balance,date where account ~ '^Assets:US:BofA:Checking' and date >= 2021-01-01 and date <= 2021-12-31;"

# right result for 2021-01-01
bean-query --numberify --format csv "example.beancount" "select balance,date where account ~ '^Assets:US:BofA:Checking' and date <= 2021-12-31;" | grep 2021

# right result for 2021-01-01
bean-query --numberify --format csv "example.beancount" "select balance,date where account ~ '^Assets:US:BofA:Checking';" | grep 2021

# right result for 2021-01-01
fava example.beancount &
firefox http://127.0.0.1:5000/example-beancount-file/account/Assets:US:BofA:Checking/?time=2021
```

## Results

bean-query with start date and end date (wrong)
```csv
-4.00,2021-01-04
```

bean-query without start date, with end date + grep (right)
```csv
8136.87,2021-01-04
```

bean-query without start date or end date + grep (right)
```csv
8136.87,2021-01-04
```

Fava with year (right)
| Date      | F | Payee/Narration              | Position | Price | Cost | Change    | Balance     |
| --------- | - | ---------------------------- | -------- | ----- | ---- | --------- | ----------- |
|2021-01-04 | * | BANK FEES - Monthly bank fee |          |       |      | -4.00 USD | 8136.87 USD |

**Comment by AlphaJack** [comment]
Why is it expected? Fava is returning a different value when filtering by year

So there is no way to obtain only values for 2021 and `8136.87,2021-01-04` without using `date <=` and `grep 2021`?

Futher queries:

```bash

bean-query --numberify --format csv "example.beancount" "select balance,date from year = 2021 where account ~ '^Assets:US:BofA:Checking';" | grep 2021-01-04
#   -4.00,2021-01-04
#-2404.00,2021-01-04

bean-query --numberify --format csv "example.beancount" "select balance,date where account ~ '^Assets:US:BofA:Checking' and date = 2021-01-04;" | grep 2021-01-04
#   -4.00,2021-01-04
#-2404.00,2021-01-04

bean-query --numberify --format csv "example.beancount" "select balance,date where account ~ '^Assets:US:BofA:Checking' and date <= 2022-01-04;" | grep 2021-01-04
# 8136.87,2021-01-04
# 5736.87,2021-01-04
```

**Comment by dnicolodi** [comment]
> Why is it expected? 

Because this is how the `balance` column is defined. The `balance` column is the cumulative balance of the selected rows, as documented https://beancount.github.io/docs/beancount_query_language.html#entry-data-columns

> Fava is returning a different value when filtering by year

The answer is 42. But that is not what the balance columns returns.

> So there is no way to obtain only values for 2021 and `8136.87,2021-01-04` without using `date <=` and `grep 2021`?

You can do that with a sub-query:
```
SELECT * 
FROM (
  SELECT
    balance, 
    date 
  FROM #postings 
  WHERE
    account ~ '^Assets:US:BofA:Checking') 
WHERE 
  date = 2021-01-04
```

**Comment by AlphaJack** [comment]
I'm getting the following error with your query:

```
ERROR: Queries from nested SELECT are not supported yet.
```

**Comment by dnicolodi** [comment]
You are not using beanquery from this repository or a very old version of it.
