### ISSUE TITLE
escape comma in csv outputs

### ISSUE THREAD

**Issue by maxheld83** [beancount/beanquery#164]
Currently:

```
1970-01-01 * "Acme Inc" "Lorem, Ipsum"
  Assets:Foo -1 USD
  Assets:Bar
```

when run through `bean-query --format=csv`,

becomes

```
acme inc,lorem, ipsum
```

which is incorrect and leads to problems in downstream processing.

```
acme inc,"lorem, ipsum"
```

would be better.

**Comment by dnicolodi** [comment]
It works as expected here:
```console
$ python -m beanquery tests/test31.beans 'select payee, narration' --format=csv
payee,narration
Acme Inc,"Lorem, Ipsum"
Acme Inc,"Lorem, Ipsum"
```
How did you test this?

**Comment by maxheld83** [comment]
apologies, the issue was caused by a downstream parser that I was using.

I cannot reproduce any issue with beanquery.
