### ISSUE TITLE
pager $PAGER no longer working

### ISSUE THREAD

**Issue by tbm** [beancount/beanquery#198]
beanquery/shell.py has:
```
    pager: str = ''
```

but beancount utils/pager.py does:
```
    if command is None:
        command = os.environ.get("PAGER", DEFAULT_PAGER)
    if not command:
        command = DEFAULT_PAGER
```

The first if is not true because `command` is not `None`; it's the empty string.  So we always end up with `DEFAULT_PAGER`, even when the environment variable `$PAGER` is set.

**Comment by dnicolodi** [comment]
Thanks @tbm for reporting this issue (and other issues). While fixing this, I started wondering whether the current interface makes sense. Would it be better to have the `pager` option take a boolean to indicate whether the pager specified in the `$PAGER` environment variable should be used or not? I loosely model the `bean-query` interface on the `sqlite3` one but `sqlite3` does not implement pager support. `pgsql` does, but implements only the boolean option. What do you think?

**Comment by dnicolodi** [comment]
It also make sense to remove the pager support code from beancont and move it into beanquery, as I don't think it is used in beancount and moving the implementation into beanquery may allow some simplifications (there are quite a few levels of indirection right now).

**Comment by tbm** [comment]
I'm not really the right person to ask design questions but I thought $PAGER should be used when set. I don't know what sqlite3 or pgsql does.

**Comment by tbm** [comment]
> It also make sense to remove the pager support code from beancont and move it into beanquery

I was surprised that `beancount/utils/pager.py` exists.  Now that beanquery has been split out, I agree I don't see the value of beancount providing this pager module.

**Comment by tbm** [comment]
> I'm not really the right person to ask design questions but I thought $PAGER should be used when set.

But to add: to me, if there's a generic pager function, the ability to pass `command` to specify a specific pager than the one in $PAGER makes sense.  But I'm not sure if bean-query needs that complexity.

**Comment by dnicolodi** [comment]
The thing is that till very recently, `bean-query` didn't have a configuration file, thus the pager setting could not be persisted. Thus I don't think anyone ever set it to something that was not the default. I'm temped to simplify things slightly and just use `$PAGER` if the `pager` setting is true or not page the output otherwise. `pgsql` does this and if this is fine for PostgreSQL, it is probably fine for bean-query too.

**Comment by tbm** [comment]
Sounds good to me!
