### ISSUE TITLE
implement named parameterized queries

### ISSUE THREAD

**Issue by WolfgangFahl** [beancount/beanquery#201]
see e.g. https://github.com/WolfgangFahl/pyLoDStorage/blob/master/lodstorage/params.py

which does jinja compatible parameter handling and is used in https://github.com/WolfgangFahl/snapquery

with demos at https://snapquery.bitplan.com/ and https://genwiki2024.bitplan.com/

<img width="969" alt="grafik" src="https://github.com/user-attachments/assets/de588ce6-df42-49ca-92b8-f2b4584ca589">
<img width="1098" alt="grafik" src="https://github.com/user-attachments/assets/5f884a6e-f40b-4fb9-9d32-e293d6563d60">

**Comment by dnicolodi** [comment]
From the provided links I'm not able to understand what the feature you are asking would be doing. The examples provided are web GUIs for running some sort of queries. beanquery does not have a GUI, only an interactive shell. How do you foresee this feature to work in the interactive shell? beanquery does not even have a very well defined concept of named queries. It can load named queries defined in Beancount ledgers with the `query` directive. Are you proposing to extend this facility with the possibility of passing parameters to the queries stored in Beancount ledgers? How would the user interface for this functionality look like?

In particular, I don't understand the reference to "ninja compatible parameter handling". This seems to imply that query parameters are interpolated textually into the query string. This is a very bad idea and results in having to deal with escaping of the substituted parameters when composing the query, which is very fragile. beanquery has support for parametrized queries like most SQL client implementations that does not rely on textual manipulation of the query string.

**Comment by dnicolodi** [comment]
beanquery supports queries with parameters. parameters placeholders have the same style as defined in the Python DB-API with paramstyles `format` or `pyformat` as implemented for example by the psicopg https://www.psycopg.org/psycopg3/docs/basic/params.html

IIUC, the main difference from what you propose is that the parameters are textually replaced in the query string. What beanquery does (and what other SQL and SQL-like client libraries do) is to use placeholders that are bound to values at query execution time.

beanquery is not going to provide a text substitution implementation of query parameters.

**Comment by WolfgangFahl** [comment]
Thanks i will happily try this out. Currently my main obstacle is the incompatibility of beancount 3 and beancount 2 - how can i use beanquery as a component without automatically getting beancount2 ? Could you make beanquery available as a separate pypi release?

**Comment by dnicolodi** [comment]
I don't understand what you mean. beanquery *is* a separate package.

**Comment by WolfgangFahl** [comment]
I found https://pypi.org/project/beanquery/  with _This is a fork of beancount.query that is intended to eventually replace it. This is currently work in progress._ The dev0 label the statement and the missing badge in the README here confused me a bit. I am now going to try to use it.

**Comment by dnicolodi** [comment]
The attentive observer would have spotted the fact that the "Homepage" link of the package on PyPI points to exactly this GitHub repository.
