### ISSUE TITLE
GROUP BY and financial year

### ISSUE THREAD

**Issue by tbm** [beancount/beanquery#37]
SELECT YEAR, SUM(position) WHERE account ~ '^Income' GROUP BY YEAR ORDER BY YEAR

Unfortunately, the financial year is not the calendar year.

It would be nice for BQL to somehow have the concept of a financial year.

(FWIW, Fava has support for financial years)

**Comment by dnicolodi** [comment]
Another approach could be a `truncate()` function similar to the PostgreSQL's one that would allow to extract different facets from a date: `truncate(date, "fiscal-year")`, `truncate(date, "fiscal-quarter")`, `truncate(date, "quarter")`, and a new option in Beancount to set the fiscal year rules, something like `option "fiscal-year" "..."` where `"..."` is the definition of the fiscal year in some suitable format.

**Comment by tbm** [comment]
I've done some tests and this seems to work as expected, thank you!

**Comment by dnicolodi** [comment]
Thanks for testing. The implementation of `date_bin()` for strides with month or longer units is a fairly naive increment in a loop (AFAIK, it is impossible to implement the general case in a more efficient way, and this is most likely why the SQL standard function does not allow strides with month or longer units, and I didn't put in the effort to check whether any common special case can optimized) thus I recommend to keep the origin as close as possible as the values to bin.
