### ISSUE TITLE
Add INT() function to BQL

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#38]
**[Original report](https://bitbucket.org/blais/beancount/issue/415) by Red Street (GitHub: [redstreet](https://github.com/redstreet)).**

----------------------------------------

INT\(str/int/Decimal\): converts to an integer and returns it.

Example use case: convert metadata into an integer, and use it in computations.

**Comment by dnicolodi** [comment]
Implemented in 050f07ea0acf101d0c2a9e1df127c2f61af288b3
