### ISSUE TITLE
Make ANY_META case insensitive?

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#42]
**[Original report](https://bitbucket.org/blais/beancount/issue/352) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

This is just an idea so feel free to close if you disagree.

Metadata tags have start with a lowercase letter.  I wonder if ANY_META should ignore the case of the first letter (i.e. basically do a `lcfirst` on the argument).

I guess, more broadly, should metadata tags be completely case insensitive? Currently they aren't.

Actually, the more I think about it, I think doing the `lcfirst` as suggested doesn't make sense if the decision is to keep the case sensitivity.  People used to uppercase tags (e.g. from ledger) should just get used to lowercase.

**Comment by dnicolodi** [comment]
To make the first letter of metadata keywords lower case seems way too magic. Metadata keywords must start with a lower case letter, but are case sensitive, thus making the metadata lookup case insensitive does not seem to be a good idea.
