### ISSUE TITLE
bsql: unsupported operand type(s) for &: 'NoneType' and 'bool'

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#45]
**[Original report](https://bitbucket.org/blais/beancount/issue/345) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I can do this to make sure metadata does NOT exist:

```
beancount> SELECT account WHERE NOT ANY_META('program');

```

If I drop the `NOT`, it also works fine:

```
beancount> SELECT account WHERE ANY_META('program');

```

However, this fails:

```
beancount> SELECT account WHERE ANY_META('program') AND NOT ANY_META('entity');
...
    return self.operator(self.left(context), self.right(context))
TypeError: unsupported operand type(s) for &: 'NoneType' and 'bool'
```

It doesn't make sense that it works on its own but not when combined with another query of the same type.

As a workaround, `ANY_META('program')  ~ '' AND...` it works; but I think the simple query should work.

**Comment by dnicolodi** [comment]
Fixed in bf3dedf7310ba5667ce32f926d50e96132667d37 and 60d28ec05407f750aaea916cb5348c85b1aa847b
