### ISSUE TITLE
BQL: None should be considered False in boolean context

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#48]
**[Original report](https://bitbucket.org/blais/beancount/issue/335) by Stefano Zacchiroli (Bitbucket: [zacchiro](https://bitbucket.org/zacchiro), GitHub: [zacchiro](https://github.com/zacchiro)).**

----------------------------------------

The following query:
```
SELECT ANY_META('trip') AS trip, SUM(position) AS amount
WHERE account ~ '^Assets:Reimbursable'
AND ANY_META('trip')
GROUP BY trip
```
when 'trip' might be missing from some transaction fails as follows:
```
  File "/home/zack/.local/lib/python3.6/site-packages/beancount/query/query_compile.py", line 121, in __call__
    return self.operator(self.left(context), self.right(context))
  TypeError: unsupported operand type(s) for &: 'bool' and 'str'
```
the string in question is probably "None", i.e., the string representation of Python None values.

It would be nice if missing metadata could be treated as False in boolean context by BQL.

**Comment by dnicolodi** [comment]
@zacchiro  @tbm This works now. beanquery is going through some major changes that fix many of the long standing shortcomings. I would be happy if you could give the current git version a try and report back.

**Comment by tbm** [comment]
That's good to hear, @dnicolodi. Thanks for working on this!  I hope to try it out but can't promise when.

**Comment by zacchiro** [comment]
@dnicolodi thanks a lot!

Last time I tried to use bean-query with beancount v2 I couldn't due to dependency issues.
(Rechecking my notes from a discussion we had on the beancount list the reason at the time was this: "Unfortunately I cannot actually use bean-query on my own v2 beancount ledger, because I use as extension Fava's auto_commit, and Fava is incompatible with beancount v3".)

So I don't think I can test this right now, unless the above problem has evolved since. (If you know it has, a ping on this is welcome, otherwise I will eventually give it another try.)

**Comment by dnicolodi** [comment]
I remember that exchange now. Things haven't changed in this regard. However, I think that the recent improvements in beanquery are significant enough to deserve being put to good use. I may look again into making beanquery work with beancount v2. What may be a good strategy to make this work without too much trouble just came to mind.

**Comment by tbm** [comment]
FWIW, the v2 issue was also the main reason I wasn't sure when I'd be able to test it.  Making it work with v2 would be great!

**Comment by dnicolodi** [comment]
Turns out that some extra motivation was everything it took to make the test work with beancount v2, see #79. I am now confident that beanquery can be used with beancount releases 2.3.4 and later. I had some weird test errors in 2.3.0 but I didn't investigate further. Testing should be a mere `python -m pip install beanquery` away now. Please let me know how this works for you.

**Comment by tbm** [comment]
Thank you, @dnicolodi. This is wonderful!

**Comment by zacchiro** [comment]
@dnicolodi thanks! I confirm I can now install (standalone) beanquery with beancount 2.x.
However I've some queries (not all) that no longer work after the change, and one error message is potentially related to this issue we are discussing here.
Consider the following query:
```
3000-01-01 query "reimbursable_by_debtor" "
  SELECT ANY_META('debtor') AS debtor, SUM(position) AS amount
  WHERE account ~ '^Assets:Reimbursable'
  AND ANY_META('debtor') != NULL
  GROUP BY debtor
  ORDER BY debtor
  "
```
It works with legacy beanquery, but it fails with standalone beanquery as follows:
```
ERROR: Operator equal(object, NoneType) not supported.
```
(Note: I don't want to hijack this issue with something unrelated, so please shout if I should file this as a separate issue.)

But other queries do work, so YAY, I can start dipping my toes into beanquery next generation :-)

**Comment by dnicolodi** [comment]
Thank you for testing!

The behavior you report is actually the demonstration that things work as intended. The `!= NULL` part of the query is a weird construct that had to be used before when beanquery was not very rigorous in dealing with NULL values. If you just remove it, things should work as expected.

In SQL comparing NULL values returns always NULL, which is false in boolean context. Thus the SQL equivalent of your query would never return any row. BQL deviated from this and allowed comparing NULL values but now that NULL values are handled correctly keeping this behavior is a mess and results in extremely complex semantics. I thus decided to forbid explicit comparisons with NULL. If you want to be explicit (in the case you have "debtor" metadata entries that are present but with a false value, like empty strings or 0) you can use the `IS NOT NULL` operator.

I hope this makes sense. There are some choices I made to allow strict typing in BQL mixed with weak typing for metadata values that must be documented, but writing documentation is less fun than writing code...

**Comment by dnicolodi** [comment]
I've never done any sophisticated work on relational databases and I always thought the handling of NULL values in SQL to be funny at best. Now that I'm working on a query language myself I understand why things work that way: anything else results in inconsistent behavior. Martin basing BQL on SQL was forward looking in this sense.

**Comment by zacchiro** [comment]
Oh, yeah, this totally makes sense (I was so used to using BQL this way that, in spite of using SQL quite heavily in other contexts, I didn't think of this). I confirm it works as intended. Now almost all my previous queries work fine with standalone beancount, except this one:
```
3000-01-01 query "todo" "
  JOURNAL '.*'
  FROM flag = '!'
  OR 'todo' IN tags
  "
```
which fails with:
```
ERROR: Operator contains(str, set) not supported.
```
Should I file this as a separate issue?
(FWIW, the previous behavior was consistent with the use of SQL `IN` operator.)

**Comment by dnicolodi** [comment]
I can only explain this with the fact that there are no tests for the `IN` operator. I obviously screw up the function signature for it. No need to open an issue: I'll fix it straight away. Thank you very much for testing.

**Comment by dnicolodi** [comment]
I just pushed the fix for the `IN` operator. As compensation you also get support for list literals. You can now write something like:
```
SELECT entry_meta('trip'), sum(position) WHERE entry_meta('trip') IN ('Paris', 'Boulder') GROUP BY 1
```

**Comment by zacchiro** [comment]
On Wed, Apr 06, 2022 at 02:26:30PM -0700, Daniele Nicolodi wrote:
> I just pushed the fix for the `IN` operator.

Awesome, I just tested it and I confirm it works for me too! (I didn't
have yet a use case for list literals, but that's nifty as well :-))

Thanks a lot!
