### ISSUE TITLE
Allow arithmetic operations on dates

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#56]
**[Original report](https://bitbucket.org/blais/beancount/issue/115) by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

See https://groups.google.com/d/msgid/beancount/33204474-7109-4766-a1d0-eac5b806d0e8%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by dnicolodi** [comment]
Implemented in #33
