### ISSUE TITLE
Implement pivot table tool & make sure it works to produce monthly aggregations

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#61]
See TODO list for more details.

> Is there a way to compare balances by month and/or by year.  Ie: say I wanted to know how much I spent on each category for each of the last 24 months?

Not yet, but I've been thinking about that and wanting it for a long while.
I think the most generic and flexible way to implement that would be via a combination of bean-query generating a table like this:

```
  Month  Account  Balance
  ...         ...            ...
```

and combining that with a separate tool that would pivot Balance on Month vs. Account, to produce something like this:

```
                Month
                6/15      7/15     8/15
   Account 
   Expenses:Restaurant   ... ... ...
```

**Comment by dnicolodi** [comment]
#94 contains more detailed description of the functionality. Implemented in #95.
