### ISSUE TITLE
bean-query: ORDER BY does not accept per-keyword sort direction

### ISSUE THREAD

**Issue by blais** [beancount/beanquery#63]
**[Original report](https://bitbucket.org/blais/beancount/issue/40) by Harpreet Sangha (Bitbucket: [eliptus](https://bitbucket.org/eliptus), GitHub: [eliptus](https://github.com/eliptus)).**

----------------------------------------

I noticed that when using ORDER BY with bean-query sort direction cannot be specified per keyword.

For example:
beancount> SELECT year, account, COST(SUM(position)) AS total WHERE account ~ "^Expenses:" GROUP BY 1, 2 ORDER BY 1 ASC, 2 DESC
ERROR: Syntax error near ',' (at 108)
  SELECT year, account, COST(SUM(position)) AS total WHERE account ~ "^Expenses:" GROUP BY 1, 2 ORDER BY 1 ASC, 2 DESC

**Comment by dnicolodi** [comment]
Implemented in #28.
