### ISSUE TITLE
PLY is not maintained anymore as a package on PyPI

### ISSUE THREAD

**Issue by dnicolodi** [beancount/beanquery#78]
For reasons that I'm not sure I understand, the PLY author decided to stop upload new version of PLY to PyPI and suggests to embed a copy in the projects that use it https://github.com/dabeaz/ply/blob/559a7a1feabb0853be79d4f4dd9e9e9e5ea0d08c/README.md?plain=1#L30 and dabeaz/ply#255 

I am not aware of any bug fixed in PLY after the last release available on PyPI, but moving forward we can think about copying a more recent version into the repository or to move to SLY.

**Comment by blais** [comment]
Thanks for pointing it out. I didn't know about SLY. Things change, situation normal.

**Comment by dnicolodi** [comment]
He's a very good speaker. I'll definitely watch the talk. Sometime I wonder how long it prepares for his talks. The one on concurrency where it lives codes all the demos is brilliant.

**Comment by dnicolodi** [comment]
Just finished to watch the talk. I'm blown away. SLY is pure magic! I have no idea how some of the things that it does are actually possible.

**Comment by dnicolodi** [comment]
The parser as been re-implemented using TatSu. PLY is not a dependency anymore.
